import 'package:machuco/models/room/room_models.dart';

List<RoomTypeData> buildRoomTypeMockData() => const [
  RoomTypeData(id: 'type-suite', motelId: '1', name: 'Suite'),
  RoomTypeData(id: 'type-loft', motelId: '1', name: 'Loft'),
  RoomTypeData(id: 'type-cabin', motelId: '1', name: 'Cabina'),
  RoomTypeData(id: 'type-studio', motelId: '2', name: 'Studio'),
];

List<RoomVisualData> buildRoomMockData() => const [
  RoomVisualData(
    id: 'room-101',
    motelId: '1',
    name: 'Suite Aurora',
    description: 'Suite premium con acceso privado y enfoque en privacidad.',
    idType: 'type-suite',
    pricePerHour: 68000,
    roomNumber: '101',
    capacity: 2,
    imageUrls: ['aurora-frontal', 'aurora-jacuzzi'],
    isActive: true,
    includedServices: ['Jacuzzi', 'Smart TV', 'Wi-Fi'],
  ),
  RoomVisualData(
    id: 'room-204',
    motelId: '1',
    name: 'Loft Neon',
    description: 'Habitación moderna con minibar, luces regulables y lounge.',
    idType: 'type-loft',
    pricePerHour: 52000,
    roomNumber: '204',
    capacity: 3,
    imageUrls: ['neon-principal'],
    isActive: true,
    includedServices: ['Minibar', 'Wi-Fi', 'Iluminación ambiental'],
  ),
  RoomVisualData(
    id: 'room-206',
    motelId: '1',
    name: 'Loft Eclipse',
    description: 'Loft de ambiente oscuro con parqueadero y climatización.',
    idType: 'type-loft',
    pricePerHour: 49000,
    roomNumber: '206',
    capacity: 2,
    imageUrls: ['eclipse-principal'],
    isActive: false,
    includedServices: ['Parqueadero', 'Aire acondicionado'],
  ),
  RoomVisualData(
    id: 'room-305',
    motelId: '3',
    name: 'Cabina Prisma',
    description: 'Opción compacta para reservas ágiles con check-in rápido.',
    idType: 'type-cabin',
    pricePerHour: 39000,
    roomNumber: '305',
    capacity: 2,
    imageUrls: ['prisma-exterior'],
    isActive: true,
    includedServices: ['Wi-Fi', 'Aire acondicionado', 'Smart TV'],
  ),
  RoomVisualData(
    id: 'room-402',
    motelId: '2',
    name: 'Studio Loto',
    description: 'Unidad versátil para grupos pequeños y parqueadero.',
    idType: 'type-studio',
    pricePerHour: 44000,
    roomNumber: '402',
    capacity: 4,
    imageUrls: ['loto-principal'],
    isActive: false,
    includedServices: ['Parqueadero', 'Wi-Fi', 'Room service'],
  ),
];
