import 'package:machuco/models/booking.dart';

/// Datos estáticos para validar las vistas. No ejecuta reglas de negocio.
abstract final class BookingController {
  static final List<Booking> clientBookings = [
    Booking(
      id: 'booking-1048',
      motelId: 'motel-eclipse',
      motelName: 'Motel Eclipse',
      roomName: 'Suite Aurora',
      roomNumber: '101',
      guestName: 'Laura Gómez',
      guestCount: 2,
      checkIn: DateTime(2026, 8, 28, 20),
      checkOut: DateTime(2026, 8, 28, 23),
      total: 204000,
      status: BookingStatus.pendingPayment,
      paymentStatus: BookingPaymentStatus.pending,
      reference: 'MC-1048',
      notes: 'Ingreso privado por parqueadero norte.',
    ),
    Booking(
      id: 'booking-1021',
      motelId: 'motel-eclipse',
      motelName: 'Motel Eclipse',
      roomName: 'Loft Neon',
      roomNumber: '204',
      guestName: 'Laura Gómez',
      guestCount: 2,
      checkIn: DateTime(2026, 8, 19, 18),
      checkOut: DateTime(2026, 8, 19, 21),
      total: 156000,
      status: BookingStatus.completed,
      paymentStatus: BookingPaymentStatus.paid,
      reference: 'MC-1021',
    ),
    Booking(
      id: 'booking-0994',
      motelId: 'motel-luna',
      motelName: 'Luna Roja',
      roomName: 'Suite Cielo',
      roomNumber: '12',
      guestName: 'Laura Gómez',
      guestCount: 2,
      checkIn: DateTime(2026, 7, 30, 22),
      checkOut: DateTime(2026, 7, 31, 1),
      total: 189000,
      status: BookingStatus.cancelled,
      paymentStatus: BookingPaymentStatus.refunded,
      reference: 'MC-0994',
    ),
  ];

  static final List<Booking> ownerBookings = [
    ...clientBookings,
    Booking(
      id: 'booking-1052',
      motelId: 'motel-eclipse',
      motelName: 'Motel Eclipse',
      roomName: 'Cabina Prisma',
      roomNumber: '305',
      guestName: 'Camilo Martínez',
      guestCount: 2,
      checkIn: DateTime(2026, 8, 29, 14),
      checkOut: DateTime(2026, 8, 29, 18),
      total: 156000,
      status: BookingStatus.confirmed,
      paymentStatus: BookingPaymentStatus.paid,
      reference: 'MC-1052',
    ),
    Booking(
      id: 'booking-1056',
      motelId: 'motel-luna',
      motelName: 'Luna Roja',
      roomName: 'Habitación Deluxe',
      roomNumber: '18',
      guestName: 'Andrea Ruiz',
      guestCount: 2,
      checkIn: DateTime(2026, 8, 30, 19),
      checkOut: DateTime(2026, 8, 30, 22),
      total: 177000,
      status: BookingStatus.confirmed,
      paymentStatus: BookingPaymentStatus.paid,
      reference: 'MC-1056',
    ),
  ];

  static const List<MotelBookingSummary> motelSummaries = [
    MotelBookingSummary(
      motelId: 'motel-eclipse',
      motelName: 'Motel Eclipse',
      city: 'Medellín',
      totalBookings: 184,
      activeBookings: 31,
      cancelledBookings: 12,
      averageBookingsPerDay: 6.1,
      occupancyRate: 78.4,
      totalRevenue: 28450000,
    ),
    MotelBookingSummary(
      motelId: 'motel-luna',
      motelName: 'Luna Roja',
      city: 'Bello',
      totalBookings: 132,
      activeBookings: 24,
      cancelledBookings: 9,
      averageBookingsPerDay: 4.4,
      occupancyRate: 69.2,
      totalRevenue: 19870000,
    ),
    MotelBookingSummary(
      motelId: 'motel-nova',
      motelName: 'Nova Suites',
      city: 'Envigado',
      totalBookings: 96,
      activeBookings: 17,
      cancelledBookings: 15,
      averageBookingsPerDay: 3.2,
      occupancyRate: 54.8,
      totalRevenue: 14200000,
    ),
  ];
}
